import torch
import torch.utils.dlpack
import torch.nn.functional as F
import threading

def test_tanh_dlpack_concurrent_conversion():
    """
    Test case to verify the correctness and thread-safety of DLPack conversion
    on tensors generated by torch.nn.functional.tanh.

    This test is based on the issue regarding intrusive caching of DLPack to reduce
    overhead. The provided C++ fix implements atomic operations to handle concurrent
    cache population. This test simulates that scenario by performing concurrent
    DLPack conversions on a tensor produced by the similar API (tanh).
    """
    # Create a random tensor
    x = torch.randn(100, 100)
    
    # Apply tanh (Similar API) to simulate an intermediate activation tensor
    # that is frequently exchanged (e.g., in model inference or training loops).
    y = F.tanh(x)

    # List to collect any exceptions or errors from threads
    errors = []

    def convert_worker():
        try:
            # Perform multiple conversions to simulate the "frequent tensor exchanges"
            # mentioned in the bug description.
            for _ in range(50):
                # Convert to DLPack
                dl_capsule = torch.utils.dlpack.to_dlpack(y)
                
                # Convert back from DLPack
                z = torch.utils.dlpack.from_dlpack(dl_capsule)
                
                # Assert correctness: The converted tensor should match the original
                assert torch.equal(y, z), "Data mismatch after DLPack roundtrip"
        except Exception as e:
            errors.append(e)

    # Create multiple threads to trigger the race condition logic
    # present in the C++ fix (std::atomic_compare_exchange_strong_explicit).
    threads = []
    num_threads = 10
    for _ in range(num_threads):
        t = threading.Thread(target=convert_worker)
        threads.append(t)
        t.start()

    # Wait for all threads to complete
    for t in threads:
        t.join()

    # Check if any thread encountered an error
    assert len(errors) == 0, f"Test failed with errors: {errors}"

    print("Test passed: Concurrent DLPack conversions on tanh output are consistent.")

if __name__ == "__main__":
    test_tanh_dlpack_concurrent_conversion()