import torch
import tensorflow as tf

def test_int64_arange_max_in_scope():
    """
    Adapts the PyTorch reproduction logic to TensorFlow using tf.compat.v1.name_scope.
    The original bug involved a crash in PyTorch's Inductor compiler when handling
    int64 tensors generated by iota (arange) passed to max.
    This test verifies that TensorFlow handles the equivalent operations correctly.
    """
    
    # Use the requested API: tf.compat.v1.name_scope
    with tf.compat.v1.name_scope("inductor_crash_repro"):
        # Inputs
        # x = torch.ones(1, 64, device='cuda', dtype=torch.int64)
        arg0_1 = tf.ones((1, 64), dtype=tf.int64)
        
        # y = torch.randn(64, 3072, device='cuda', dtype=torch.bfloat16)
        arg1_1 = tf.random.normal((64, 3072), dtype=tf.bfloat16)

        # embedding = torch.ops.aten.embedding.default(arg1_1, arg0_1)
        # PyTorch embedding: (weight, indices) -> TF embedding_lookup: (params, ids)
        embedding = tf.nn.embedding_lookup(arg1_1, arg0_1)

        # view = torch.ops.aten.view.default(embedding, [64, 3072])
        view = tf.reshape(embedding, [64, 3072])

        # unsqueeze = torch.ops.aten.unsqueeze.default(view, 0)
        unsqueeze = tf.expand_dims(view, 0)

        # expand = torch.ops.aten.expand.default(unsqueeze, [576, -1, -1])
        expand = tf.broadcast_to(unsqueeze, [576, -1, -1])

        # view_1 = torch.ops.aten.view.default(expand, [2, 8, 36, 64, 3072])
        view_1 = tf.reshape(expand, [2, 8, 36, 64, 3072])

        # permute = torch.ops.aten.permute.default(view_1, [0, 1, 3, 2, 4])
        permute = tf.transpose(view_1, [0, 1, 3, 2, 4])

        # clone = torch.ops.aten.clone.default(permute, memory_format = torch.contiguous_format)
        clone = tf.identity(permute)

        # view_2 = torch.ops.aten.view.default(clone, [2, 18432, 3072])
        view_2 = tf.reshape(clone, [2, 18432, 3072])

        # iota = torch.ops.prims.iota.default(36, start = 0, step = 1, dtype = torch.int64, device = 'cuda', requires_grad = False)
        iota = tf.range(0, 36, dtype=tf.int64)

        # view_3 = torch.ops.aten.view.default(iota, [1, 36])
        view_3 = tf.reshape(iota, [1, 36])

        # max_1 = torch.ops.aten.max.default(view_3)
        # PyTorch max on a tensor returns the maximum value.
        max_1 = tf.reduce_max(view_3)

        return max_1

if __name__ == "__main__":
    # Execute the function
    result = test_int64_arange_max_in_scope()
    
    # Verify the result
    # The iota creates [0, 1, ..., 35]. The max should be 35.
    expected = 35
    assert result.numpy() == expected, f"Expected max to be {expected}, got {result.numpy()}"
    print("Test passed. Result:", result.numpy())