import torch
import tensorflow as tf

def test_name_scope_cache_consistency():
    """
    Adapts the PyTorch torch.compile cache consistency bug to TensorFlow.
    
    Original Bug: tlparse entries (debug artifacts) were present on cache miss
    but missing/incorrect on cache hit.
    
    TF Adaptation: We verify that metadata (operation names) generated by 
    tf.keras.name_scope during the initial trace (cache miss) remains 
    consistent and present when the function is called again (cache hit).
    """
    
    # We use tf.function to simulate the compilation/caching behavior of torch.compile
    @tf.function
    def simple_model(x):
        # Using the API under test: tf.keras.name_scope
        with tf.keras.name_scope("my_custom_scope"):
            # Create an operation that will be affected by the name scope
            y = x * 2.0
            return y

    # Input data
    x = tf.constant([1.0, 2.0, 3.0])

    # --- Step 1: Cache Miss (First Trace) ---
    # This triggers the tracing of the function, similar to a torch.compile cache miss
    result_miss = simple_model(x)
    
    # Retrieve the graph definition generated during the trace
    concrete_fn = simple_model.get_concrete_function(x)
    graph_def_miss = concrete_fn.graph.as_graph_def()
    
    # Extract operation names from the "miss" trace
    # These correspond to the "tlparse entries" in the original bug
    op_names_miss = [node.name for node in graph_def_miss.node]
    
    # Filter for names that should be inside the scope
    scoped_names_miss = [name for name in op_names_miss if "my_custom_scope" in name]

    # --- Step 2: Cache Hit (Subsequent Call) ---
    # This re-uses the traced graph, similar to a torch.compile cache hit
    result_hit = simple_model(x)
    
    # Retrieve the graph definition again (it should be the cached one)
    graph_def_hit = concrete_fn.graph.as_graph_def()
    op_names_hit = [node.name for node in graph_def_hit.node]
    
    # Filter for names inside the scope
    scoped_names_hit = [name for name in op_names_hit if "my_custom_scope" in name]

    # --- Step 3: Verify Consistency ---
    # The original bug reported that specific entries were missing on cache hit.
    # We assert that the scoped names (metadata) are present in both scenarios.
    
    # 1. Ensure the scope actually affected the graph during trace
    assert len(scoped_names_miss) > 0, \
        "Test setup error: Name scope did not generate entries during trace."

    # 2. Ensure the scope entries are NOT missing on cache hit
    # This corresponds to checking for the missing  entries in the bug report
    assert len(scoped_names_hit) > 0, \
        "Bug reproduced: Name scope entries are missing on cache hit."

    # 3. Ensure strict consistency between miss and hit
    assert set(scoped_names_miss) == set(scoped_names_hit), \
        f"Inconsistency detected: Trace entries {scoped_names_miss} differ from Cache Hit entries {scoped_names_hit}"

    print("Test Passed: Name scope entries are consistent between cache miss and hit.")

if __name__ == "__main__":
    test_name_scope_cache_consistency()