import tensorflow as tf
import unittest

class TestNameScopeConsistency(unittest.TestCase):
    """
    Adapted from PyTorch Issue 166012: tlparse entries on cache hit and not are inconsistent.
    
    This test verifies the consistency of 'entries' (operation names) generated by 
    tf.compat.v1.name_scope across multiple invocations. 
    
    In the original PyTorch bug, specific debug log entries (tlparse files) were present 
    during a cache miss but missing or inconsistent during a cache hit. 
    
    Here, we simulate "Cache Miss" (first entry into scope) and "Cache Hit" (re-entry into scope)
    to ensure that the naming context (the 'entry') is applied consistently in both scenarios,
    and does not disappear or behave erratically on subsequent uses.
    """

    def test_name_scope_consistency_across_invocations(self):
        # We use a Graph context to ensure name_scope behavior is active and observable.
        # In eager mode (default in TF2), name_scope with skip_on_eager=True (default) 
        # is a no-op, which would be the ultimate "inconsistency" if expected to work.
        with tf.Graph().as_default():
            scope_name = "test_scope"
            op_name = "my_op"

            # --- Scenario 1: Cache Miss (First Invocation) ---
            # We expect the scope to be applied, creating a specific entry.
            with tf.compat.v1.name_scope(scope_name):
                # Create a constant operation
                tensor_1 = tf.constant(1.0, name=op_name)
            
            # --- Scenario 2: Cache Hit (Second Invocation) ---
            # We re-enter the scope. In TensorFlow, this typically creates a unique suffix 
            # (e.g., test_scope_1) to avoid name collisions. The core consistency check is 
            # that the scope logic is still active and the prefix is preserved, not dropped.
            with tf.compat.v1.name_scope(scope_name):
                tensor_2 = tf.constant(1.0, name=op_name)

            # --- Verification ---
            
            # 1. Verify the first run (Miss) generated the expected entry.
            # Expected name: "test_scope/my_op:0"
            self.assertIn(scope_name, tensor_1.name, 
                          f"Scope prefix missing in first run (Cache Miss). Got: {tensor_1.name}")

            # 2. Verify the second run (Hit) generated a consistent entry.
            # The bug in PyTorch was that entries were missing in the hit.
            # Here we check if the scope prefix is still present (e.g., "test_scope_1/my_op:0").
            self.assertIn(scope_name, tensor_2.name, 
                          f"Scope prefix missing in second run (Cache Hit). Inconsistency detected! Got: {tensor_2.name}")

            # 3. Verify that the entries are distinct (unique names generated for each call).
            # This confirms the system recognized the second call as a distinct event 
            # (similar to distinguishing a cache hit from a miss in logging).
            self.assertNotEqual(tensor_1.name, tensor_2.name, 
                                "Operation names should be unique across multiple scope entries")

if __name__ == "__main__":
    unittest.main()