import torch
import torch.nn as nn
from torch.export import Dim, export
import torch._dynamo

# This test case reproduces the "Constraints violated" error reported in the issue.
# The error occurs when torch.export.export encounters a guard generated by the model
# logic that is incompatible with the user-specified dynamic shape ranges.
#
# In the specific bug report, the error message was:
# "Not all values of seq = ... in the specified range seq <= 512 satisfy the generated guard
#  min(88 + 8*L['past_key_values']['key_cache'][0].size()[2]...)"
#
# This implies a constraint where an index or size calculation (88 + 8*seq) must be
# within bounds that conflict with the allowed range of seq (up to 512).

class ConstraintViolationModel(nn.Module):
    def forward(self, x):
        # x shape: (batch, seq, hidden)
        seq_len = x.size(1)
        
        # Simulate the logic that creates the conflicting guard.
        # We create a fixed buffer (e.g., a cache or table) of size 512.
        # We calculate an index based on seq_len: 88 + 8 * seq_len.
        # Accessing this index generates a guard: 0 <= 88 + 8 * seq_len < 512.
        # Solving for seq_len: -11 <= seq_len < 53.
        
        fixed_buffer = torch.zeros(512)
        index = 88 + 8 * seq_len
        
        # This access triggers the guard generation.
        # If seq_len is allowed to be up to 512 (via dynamic_shapes), but the guard
        # requires seq_len < 53, a ConstraintViolationError is raised.
        val = fixed_buffer[index]
        
        return x + val

def test_export_constraints_violated():
    # Setup example inputs
    batch_size = 2
    seq_len = 10  # This specific value works, but the range is the problem
    hidden_dim = 32
    
    example_args = (torch.randn(batch_size, seq_len, hidden_dim),)
    
    # Define dynamic shapes matching the bug report context
    # The bug report mentions "seq <= 512"
    batch_dim = Dim("batch", min=1, max=4)
    seq_dim = Dim("seq", min=1, max=512)
    
    dynamic_shapes = ({0: batch_dim, 1: seq_dim},)
    
    model = ConstraintViolationModel()
    
    # Attempt to export the model
    # We expect this to raise torch._dynamo.exc.UserError with "Constraints violated"
    try:
        ep = export(model, args=example_args, dynamic_shapes=dynamic_shapes)
        print("Export succeeded. If running on the failing torch version, this is unexpected.")
    except torch._dynamo.exc.UserError as e:
        print(f"Successfully caught UserError: {e}")
        # Verify the error message matches the issue description
        assert "Constraints violated" in str(e)
        assert "seq" in str(e)
        print("Test case reproduces the bug behavior.")

if __name__ == "__main__":
    test_export_constraints_violated()