Traceback (most recent call last):
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1144, in test_wrapper
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/jenkins/pytorch/test/test_ops_fwd_gradients.py", line 90, in test_forward_mode_AD
    self._forward_grad_helper(device, dtype, op, op.get_op(), is_inplace=False)
  File "/var/lib/jenkins/pytorch/test/test_ops_fwd_gradients.py", line 72, in _forward_grad_helper
    call_grad_test_helper()
  File "/var/lib/jenkins/pytorch/test/test_ops_fwd_gradients.py", line 60, in call_grad_test_helper
    self._grad_test_helper(
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 5507, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 5476, in _check_helper
    self.assertTrue(gradcheck(fn, gradcheck_args,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 5066, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/autograd/gradcheck.py", line 2056, in gradcheck
    return _gradcheck_helper(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/autograd/gradcheck.py", line 2102, in _gradcheck_helper
    _test_batched_grad_forward_ad(func, tupled_inputs)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/autograd/gradcheck.py", line 1113, in _test_batched_grad_forward_ad
    raise GradcheckError(
torch.autograd.gradcheck.GradcheckError: For output 0 and input 0:


gradcheck failed while testing batched gradient computation with forward-mode AD.
This test is enabled automatically when both `check_batched_grad=True`
and `check_forward_ad=True`, but can be disabled in the following ways
dependong on how the test was invoked (via a test that calls gradcheck
directly or via an autogenerated test).

If you are adding a new operator, please file an issue and then use one of the
workarounds. The workaround depends on how your test invokes gradcheck/gradgradcheck.
If the test
- manually invokes gradcheck/gradgradcheck, then call gradcheck/gradgradcheck
  with `check_batched_forward_grad=False` as a keyword argument.
- is OpInfo-based (e.g., in test_ops_gradients.py), then modify the OpInfo for the test
  to have `check_batched_forward_grad=False`


Got:
tensor([[[[-2.8447e-01, -9.3495e+00, -5.3532e+00, -3.5951e+00, -1.5118e+01],
          [-4.9727e+00,  2.9231e+00, -4.2625e+00, -4.2446e+00, -6.8072e+00],
          [-8.2585e+00, -2.0753e+00, -1.0853e+01, -7.1631e+00,  1.3434e+00],
          [-4.2797e+00, -8.0669e-01, -2.8186e-02,  2.2013e+00,  4.3493e+00],
          [ 3.1410e+01, -1.0654e+01, -7.7934e+00,  1.8163e+01, -5.7657e-01]],

         [[ 9.8514e+00, -1.3577e+01,  1.0650e+01, -9.7494e-01, -2.7145e+01],
          [-6.6174e+00,  1.2493e+01, -1.1159e+01, -7.1392e-01,  1.8421e+01],
          [ 4.5658e+00,  6.8083e+00, -1.4981e+01,  1.4305e+01,  5.9616e+00],
          [ 6.2261e+00,  1.5935e+01, -3.0237e+01,  1.1060e+01,  1.3788e+01],
          [ 1.0085e+01, -8.9507e-01,  7.5642e+00, -1.6787e+01, -7.6168e+00]]],


        [[[-1.4927e+01,  3.4556e+00,  4.4017e+00, -1.5162e+01, -7.4527e+00],
          [-2.7287e+00, -1.3091e+00, -8.6538e+00, -9.7789e+00, -8.0384e+00],
          [-1.2538e+00,  6.0543e+00, -3.8254e+00, -7.0887e+00, -1.8744e+00],
          [-4.8803e+00,  4.5239e+00,  1.1113e+00,  1.5629e+00,  3.4842e-01],
          [-2.8001e+01, -1.2116e+01, -3.0866e+00, -3.6318e+01, -4.1906e+01]],

         [[ 1.0449e+01, -2.6362e+01,  1.2353e+01,  1.3407e+01, -2.7454e+01],
          [-1.0624e+01, -1.1201e+01,  5.7881e+00,  1.1208e+00, -3.6962e+00],
          [-3.4682e+00, -4.0205e+00, -1.4549e+01,  2.4826e+01,  5.8151e+00],
          [ 9.2075e+00,  1.6675e+01, -2.7406e+01,  1.7371e+01,  4.3994e+00],
          [-4.4266e+00, -7.8691e+00,  1.6497e+01, -1.3225e+01, -1.1948e+00]]]],
       device='cuda:0', dtype=torch.float64)

Expected:
tensor([[[[-2.9027e-01, -9.3536e+00, -5.3486e+00, -3.5977e+00, -1.5119e+01],
          [-4.9721e+00,  2.9233e+00, -4.2705e+00, -4.2481e+00, -6.8140e+00],
          [-8.2617e+00, -2.0752e+00, -1.0856e+01, -7.1675e+00,  1.3423e+00],
          [-4.2926e+00, -8.0332e-01, -2.5467e-02,  2.1959e+00,  4.3515e+00],
          [ 3.1432e+01, -1.0662e+01, -7.7987e+00,  1.8175e+01, -5.7696e-01]],

         [[ 9.8491e+00, -1.3600e+01,  1.0693e+01, -1.0030e+00, -2.7173e+01],
          [-6.6263e+00,  1.2485e+01, -1.1149e+01, -7.1282e-01,  1.8417e+01],
          [ 4.5599e+00,  6.8075e+00, -1.4982e+01,  1.4312e+01,  5.9645e+00],
          [ 6.2219e+00,  1.5933e+01, -3.0237e+01,  1.1065e+01,  1.3789e+01],
          [ 1.0083e+01, -8.9486e-01,  7.5624e+00, -1.6783e+01, -7.6150e+00]]],


        [[[-1.4927e+01,  3.4556e+00,  4.4017e+00, -1.5162e+01, -7.4527e+00],
          [-2.7287e+00, -1.3091e+00, -8.6538e+00, -9.7789e+00, -8.0384e+00],
          [-1.2538e+00,  6.0543e+00, -3.8254e+00, -7.0887e+00, -1.8744e+00],
          [-4.8803e+00,  4.5239e+00,  1.1113e+00,  1.5629e+00,  3.4842e-01],
          [-2.8001e+01, -1.2116e+01, -3.0866e+00, -3.6318e+01, -4.1906e+01]],

         [[ 1.0449e+01, -2.6362e+01,  1.2353e+01,  1.3407e+01, -2.7454e+01],
          [-1.0624e+01, -1.1201e+01,  5.7881e+00,  1.1208e+00, -3.6962e+00],
          [-3.4682e+00, -4.0205e+00, -1.4549e+01,  2.4826e+01,  5.8151e+00],
          [ 9.2075e+00,  1.6675e+01, -2.7406e+01,  1.7371e+01,  4.3994e+00],
          [-4.4266e+00, -7.8691e+00,  1.6497e+01, -1.3225e+01, -1.1948e+00]]]],
       device='cuda:0', dtype=torch.float64)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 3213, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 426, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1224, in dep_fn
    return fn(slf, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1224, in dep_fn
    return fn(slf, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 1644, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_device_type.py", line 1156, in test_wrapper
    raise e_tracked from e
Exception: For output 0 and input 0:


gradcheck failed while testing batched gradient computation with forward-mode AD.
This test is enabled automatically when both `check_batched_grad=True`
and `check_forward_ad=True`, but can be disabled in the following ways
dependong on how the test was invoked (via a test that calls gradcheck
directly or via an autogenerated test).

If you are adding a new operator, please file an issue and then use one of the
workarounds. The workaround depends on how your test invokes gradcheck/gradgradcheck.
If the test
- manually invokes gradcheck/gradgradcheck, then call gradcheck/gradgradcheck
  with `check_batched_forward_grad=False` as a keyword argument.
- is OpInfo-based (e.g., in test_ops_gradients.py), then modify the OpInfo for the test
  to have `check_batched_forward_grad=False`


Got:
tensor([[[[-2.8447e-01, -9.3495e+00, -5.3532e+00, -3.5951e+00, -1.5118e+01],
          [-4.9727e+00,  2.9231e+00, -4.2625e+00, -4.2446e+00, -6.8072e+00],
          [-8.2585e+00, -2.0753e+00, -1.0853e+01, -7.1631e+00,  1.3434e+00],
          [-4.2797e+00, -8.0669e-01, -2.8186e-02,  2.2013e+00,  4.3493e+00],
          [ 3.1410e+01, -1.0654e+01, -7.7934e+00,  1.8163e+01, -5.7657e-01]],

         [[ 9.8514e+00, -1.3577e+01,  1.0650e+01, -9.7494e-01, -2.7145e+01],
          [-6.6174e+00,  1.2493e+01, -1.1159e+01, -7.1392e-01,  1.8421e+01],
          [ 4.5658e+00,  6.8083e+00, -1.4981e+01,  1.4305e+01,  5.9616e+00],
          [ 6.2261e+00,  1.5935e+01, -3.0237e+01,  1.1060e+01,  1.3788e+01],
          [ 1.0085e+01, -8.9507e-01,  7.5642e+00, -1.6787e+01, -7.6168e+00]]],


        [[[-1.4927e+01,  3.4556e+00,  4.4017e+00, -1.5162e+01, -7.4527e+00],
          [-2.7287e+00, -1.3091e+00, -8.6538e+00, -9.7789e+00, -8.0384e+00],
          [-1.2538e+00,  6.0543e+00, -3.8254e+00, -7.0887e+00, -1.8744e+00],
          [-4.8803e+00,  4.5239e+00,  1.1113e+00,  1.5629e+00,  3.4842e-01],
          [-2.8001e+01, -1.2116e+01, -3.0866e+00, -3.6318e+01, -4.1906e+01]],

         [[ 1.0449e+01, -2.6362e+01,  1.2353e+01,  1.3407e+01, -2.7454e+01],
          [-1.0624e+01, -1.1201e+01,  5.7881e+00,  1.1208e+00, -3.6962e+00],
          [-3.4682e+00, -4.0205e+00, -1.4549e+01,  2.4826e+01,  5.8151e+00],
          [ 9.2075e+00,  1.6675e+01, -2.7406e+01,  1.7371e+01,  4.3994e+00],
          [-4.4266e+00, -7.8691e+00,  1.6497e+01, -1.3225e+01, -1.1948e+00]]]],
       device='cuda:0', dtype=torch.float64)

Expected:
tensor([[[[-2.9027e-01, -9.3536e+00, -5.3486e+00, -3.5977e+00, -1.5119e+01],
          [-4.9721e+00,  2.9233e+00, -4.2705e+00, -4.2481e+00, -6.8140e+00],
          [-8.2617e+00, -2.0752e+00, -1.0856e+01, -7.1675e+00,  1.3423e+00],
          [-4.2926e+00, -8.0332e-01, -2.5467e-02,  2.1959e+00,  4.3515e+00],
          [ 3.1432e+01, -1.0662e+01, -7.7987e+00,  1.8175e+01, -5.7696e-01]],

         [[ 9.8491e+00, -1.3600e+01,  1.0693e+01, -1.0030e+00, -2.7173e+01],
          [-6.6263e+00,  1.2485e+01, -1.1149e+01, -7.1282e-01,  1.8417e+01],
          [ 4.5599e+00,  6.8075e+00, -1.4982e+01,  1.4312e+01,  5.9645e+00],
          [ 6.2219e+00,  1.5933e+01, -3.0237e+01,  1.1065e+01,  1.3789e+01],
          [ 1.0083e+01, -8.9486e-01,  7.5624e+00, -1.6783e+01, -7.6150e+00]]],


        [[[-1.4927e+01,  3.4556e+00,  4.4017e+00, -1.5162e+01, -7.4527e+00],
          [-2.7287e+00, -1.3091e+00, -8.6538e+00, -9.7789e+00, -8.0384e+00],
          [-1.2538e+00,  6.0543e+00, -3.8254e+00, -7.0887e+00, -1.8744e+00],
          [-4.8803e+00,  4.5239e+00,  1.1113e+00,  1.5629e+00,  3.4842e-01],
          [-2.8001e+01, -1.2116e+01, -3.0866e+00, -3.6318e+01, -4.1906e+01]],

         [[ 1.0449e+01, -2.6362e+01,  1.2353e+01,  1.3407e+01, -2.7454e+01],
          [-1.0624e+01, -1.1201e+01,  5.7881e+00,  1.1208e+00, -3.6962e+00],
          [-3.4682e+00, -4.0205e+00, -1.4549e+01,  2.4826e+01,  5.8151e+00],
          [ 9.2075e+00,  1.6675e+01, -2.7406e+01,  1.7371e+01,  4.3994e+00],
          [-4.4266e+00, -7.8691e+00,  1.6497e+01, -1.3225e+01, -1.1948e+00]]]],
       device='cuda:0', dtype=torch.float64)

Caused by sample input at index 9: SampleInput(input=Tensor[size=(2, 5, 5), device="cuda:0", dtype=torch.float64], args=TensorList[Tensor[size=(2, 5, 5), device="cuda:0", dtype=torch.float64, contiguous=False]], kwargs={}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
    PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=9 PYTORCH_TEST_WITH_ROCM=1 python test/test_ops_fwd_gradients.py TestFwdGradientsCUDA.test_forward_mode_AD_cholesky_solve_cuda_float64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0