import torch
import torch.distributed as dist
import os

# Fix: Handle environments where torch.compile is not available (PyTorch < 2.0)
if not hasattr(torch, 'compile'):
    # Create a dummy decorator that mimics torch.compile behavior (identity function)
    def dummy_compile(*args, **kwargs):
        def decorator(func):
            return func
        return decorator
    torch.compile = dummy_compile

def main():
    # Setup minimal distributed environment for single process
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group("gloo", rank=0, world_size=1)

    @torch.compile(fullgraph=False, backend="eager")
    def func(a):
        # Adaptation: Use the list generated by tolist() with the similar API
        # torch.distributed.broadcast_object_list.
        # This verifies if the similar API works correctly within a compiled graph
        # when handling lists of scalar objects derived from tensors.
        obj_list = a.tolist()
        
        # Call the similar API
        dist.broadcast_object_list(obj_list, src=0)
        
        # Use the broadcasted values
        return a * obj_list[0] * obj_list[1]

    input_tensor = torch.tensor([1, 2])
    result = func(input_tensor)
    
    # Assertion to verify correctness
    expected = input_tensor * 1 * 2
    assert torch.equal(result, expected), f"Test failed: {result} != {expected}"
    
    print("Test passed successfully.")
    
    dist.destroy_process_group()

if __name__ == "__main__":
    main()