def test_stateless_truncated_normal_int64_max():
    """
    Test case derived from PyTorch Issue 164465.
    
    The original issue involves a crash in torch.compile when processing
    int64 tensors generated by an iota operation, followed by a view and max.
    
    This test adapts the logic to TensorFlow using the similar API
    `tf.random.stateless_truncated_normal`. It verifies that generating
    data, casting to int64 (to mimic the specific crash condition), reshaping,
    and reducing (max) works correctly in TensorFlow's compiled graph mode (XLA).
    """
    
    # Attempt to import TensorFlow and handle environment dependency issues
    try:
        import tensorflow as tf
    except ImportError as e:
        # Check for the specific GLIBCXX error mentioned in the traceback
        if "GLIBCXX" in str(e):
            print("Test skipped: TensorFlow cannot be imported due to a system library incompatibility (GLIBCXX).")
            print(f"Error details: {e}")
            return
        else:
            # Handle other import errors (e.g., TF not installed)
            print(f"Test skipped: TensorFlow is not installed. Error: {e}")
            return
    
    # Use tf.function with jit_compile=True to mimic torch.compile
    @tf.function(jit_compile=True)
    def compiled_func():
        # 1. Generate data using the similar API
        # The original bug used torch.ops.prims.iota (int64).
        # stateless_truncated_normal generates floats, so we cast to int64 
        # to preserve the "int64 + max" logic of the crash.
        seed = [1, 2]
        shape = [36]
        data = tf.random.stateless_truncated_normal(shape, seed=seed, dtype=tf.float32)
        
        # Cast to int64 to stress the reduction logic
        data_int64 = tf.cast(data, tf.int64)
        
        # 2. Reshape (mimic torch.ops.aten.view.default)
        view = tf.reshape(data_int64, [1, 36])
        
        # 3. Max (mimic torch.ops.aten.max.default)
        max_val = tf.math.reduce_max(view)
        
        return max_val

    # Execute the test
    try:
        result = compiled_func()
        # Assertion to ensure the operation completed and returned a scalar
        assert result.shape == (), f"Expected scalar output, got shape {result.shape}"
        print("Test passed successfully.")
        return result
    except Exception as e:
        print(f"Test failed with error: {e}")
        raise

if __name__ == "__main__":
    test_stateless_truncated_normal_int64_max()